pingidentity/dvlint-base-rule-pack

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-teleport-001/TeleportRule.js
- Resolved issue with dv-rule-teleport-001 where an incorrect error and clean event occured
> Version 1.0.0

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-node-001/tests/IgnoreRules.expect.json
- rules/dv-rule-node-001/tests/NodeRule.expect.json
- rules/dv-rule-node-002/DisabledNodeRule.js
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
Bug fix : PingOneFlowRule
Text changes
> Dv 14890 new rules fix

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-teleport-001/TeleportRule.js
- rules/dv-rule-teleport-001/tests/TeleportRule.expect.json
- rules/dv-rule-teleport-001/tests/TeleportSchemaMismatch.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
Added recommendation Args and added changes for  teleportNode rule when  node title is not available
> Dv 15563 recommendation args added

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-teleport-001/TeleportRule.js
- rules/dv-rule-teleport-001/tests/TeleportRule.expect.json
- rules/dv-rule-teleport-001/tests/TeleportSchemaMismatch.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
Added recommendation Args and added changes for teleportNode rule when node title is not available
> Release 1.0.7

- docs/rules.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-node-002/DisabledNodeRule.js
- rules/dv-rule-node-002/tests/DisabledNodeRule.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/ReferenceNodeRule.expect.json
- rules/dv-rule-variables-001/tests/ReferenceNodeRule.json
Added new rule for node iD reference of global variable and some fixes
> DV-15655 | Variable node id reference rule

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-debug-off-001/DebugOffRule.js
- rules/dv-rule-debug-off-001/tests/DebugOffRule.expect.json
- rules/dv-rule-empty-flow-001/EmptyFlowRule.js
- rules/dv-rule-logo-001/LogoRule.js
- rules/dv-rule-logo-001/tests/LogoRule.expect.json
- rules/dv-rule-multi-start-001/MultiStartRule.js
- rules/dv-rule-multi-start-001/tests/MultiStartRule.expect.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-node-001/tests/IgnoreRules.expect.json
- rules/dv-rule-node-001/tests/NodeRule.expect.json
- rules/dv-rule-teleport-001/TeleportRule.js
- rules/dv-rule-teleport-001/tests/TeleportRule.expect.json
- rules/dv-rule-teleport-001/tests/TeleportSchemaMismatch.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/ReferenceNodeRule.expect.json
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
- Adding flowId to all errors to account for any subflows in the flow.json
> Release 1.0.9

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-node-002/DisabledNodeRule.js
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- Updated flowId in a couple of rules
> Release 1.1.0

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-subflow-001/SubflowRule.js
> Release 1.1.1

- docs/rules.json
- rules/dv-rule-multi-start-001/MultiStartRule.js
- rules/dv-rule-multi-start-001/tests/MultiStartRule.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/ReferenceNodeRule.expect.json
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
DV-16015: variable rule adding nodeIds to unused and undefined variable rule
DV-16014 : remove identifier field before validation in p1sso connector
> Variable rule enhancement, p1sso identifier property handled

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-multi-start-001/MultiStartRule.js
- rules/dv-rule-multi-start-001/tests/MultiStartRule.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/ReferenceNodeRule.expect.json
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
Variable rule enhancement, p1sso identifier property handled
> Release 1.1.3

- docs/rules.json
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/SubflowRule2.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
DV-15810: NodeId added in Subflow rule :circular dependency.
Unused variable  rule changed to  best practice.
> NodeId added in Subflow rule :circular dependency

- docs/rules.json
- package.json
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/SubflowRule2.expect.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
NodeId added in Subflow rule :circular dependency
> Release 1.1.4

- docs/rules.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-node-001/tests/NodeRule.expect.json
- rules/dv-rule-node-001/tests/NodeRule.json
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- rules/dv-rule-pingOneFlow-001/tests/PingOneFlowRule.json
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/SubflowRule1.expect.json
- rules/dv-rule-teleport-001/TeleportRule.js
- rules/dv-rule-teleport-001/tests/TeleportRule.expect.json
- rules/dv-rule-teleport-001/tests/TeleportSchemaMismatch.expect.json
- rules/dv-rule-teleport-001/tests/TeleportSchemaMismatch.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
Around 16 new rules are getting added . Details can be found here https://docs.google.com/spreadsheets/d/1fgMKURRUCnhid8VCJjT4Prla05eJ_MEDb9AHbUvr-2g/edit?gid=0#gid=0
> DV-17396 | New rules Q2 25

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-node-001/tests/NodeRule.expect.json
- rules/dv-rule-node-001/tests/NodeRule.json
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- rules/dv-rule-pingOneFlow-001/tests/PingOneFlowRule.json
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/SubflowRule1.expect.json
- rules/dv-rule-teleport-001/TeleportRule.js
- rules/dv-rule-teleport-001/tests/TeleportRule.expect.json
- rules/dv-rule-teleport-001/tests/TeleportSchemaMismatch.expect.json
- rules/dv-rule-teleport-001/tests/TeleportSchemaMismatch.json
- rules/dv-rule-variables-001/VariableRule.js
- rules/dv-rule-variables-001/tests/VariableRule.expect.json
Adding New Rules
- "Expire Flow Instance Cache" enabled in an intermediate node
- Missing site key configuration for reCAPTCHA
- Incorrect 'Additional Fields in the Response' in Send Success JSON Response capability
- Incorrect 'Additional Fields in the Response' in Send Error JSON Response capability
- Global variable usage in Custom HTML Template script
- Global variable usage in Custom Function code
- Missing 'Property Name' for Output Fields in Custom HTML Template capability
- Invalid configurations for 'A == B (Multiple Conditions)' capability
- Define at least one expected outcome values for the 'A == B (Multiple Conditions)' capability to ensure correct flow branching
- Invalid output mapping for 'A == B (Multiple Conditions)' capability
- Unmapped outcome(s) in 'A == B (Multiple …
> Release 1.1.6

- docs/rules.json
- dv-rule-missingField-001/MissingFieldRule.js
- dv-rule-missingField-001/tests/MissingFieldRule.expect.json
- dv-rule-missingField-001/tests/MissingFieldRule.json
- rules/dv-rule-AEqualsBMultipleCondition-001/AEqualsBMultipleConditionRule.js
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/AEqualsBMultipleCondition.expect.json
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/AEqualsBMultipleCondition.json
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/NoCoditionBranch.json
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/NoConditionBranch.expect.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-globalVariable-001/tests/GlobalVariableUsage.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableUsage.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-node-001/tests/NodeRule.expect.json
- rules/dv-rule-subflow-001/tests/SubflowRule1.expect.json
- rules/dv-rule-subflow-001/tests/SubflowRule1.json
- rules/dv-rule-validFields-001/ValidFieldsRule.js
- rules/dv-rule-validFields-001/tests/ValidFieldsRule.expect.json
- rules/dv-rule-validFields-001/tests/ValidFieldsRule.json
- New rules segregated in multiple categories
- Added unit tests
> Dv 17396 new rules unit tests

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-globalVariable-001/tests/GlobalVariableUsage.expect.json
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- rules/dv-rule-teleport-001/TeleportRule.js
> Release 1.1.8

- docs/rules.json
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- rules/dv-rule-teleport-001/TeleportRule.js
- rules/dv-rule-validFields-001/ValidFieldsRule.js
Bug Fix
Pingone flow false node rule 
Additional Fields in the Response rule
Teleport rule
> p1Flow false node rule and additionalProperty rule bug fix

- docs/rules.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-globalVariable-001/tests/GlobalVariableConnectorConfiguration.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableConnectorConfiguration.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableLexisAndSecurId.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableLexisAndSecurId.json
- Connector configuration, global variable check
- Handle multiple code snippet blocks in one custom screen tab of capabilities
> Connector configuration, global variable check

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-globalVariable-001/tests/GlobalVariableConnectorConfiguration.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableConnectorConfiguration.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableLexisAndSecurId.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableLexisAndSecurId.json
- Connector configuration, global variable check
- Handle multiple code snippet blocks in one custom screen tab of capabilities
> Release 1.2.1

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-globalVariable-001/tests/GlobalVariableRule1.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableRule1.json
More properties for few connectors added in scope of globalVariable rule
> Release 1.2.2

- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
Handle trigger complete branch in p1FalsePathRule
> Handle trigger complete branch in p1FalsePathRule

- docs/rules.json
- rules/dv-rule-AEqualsBMultipleCondition-001/AEqualsBMultipleConditionRule.js
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/AEqualsBMultipleCondition.expect.json
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/NoConditionBranch.expect.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-globalVariable-001/tests/GlobalVariableConnectorConfiguration.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableLexisAndSecurId.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableRule1.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableUsage.expect.json
- rules/dv-rule-globalVariable-001/tests/GlobalVariableusageRule3.expect.json
- rules/dv-rule-multi-start-001/MultiStartRule.js
- rules/dv-rule-node-001/NodeRule.js
- rules/dv-rule-node-001/tests/IgnoreRules.expect.json
- rules/dv-rule-node-001/tests/NodeRule.expect.json
- rules/dv-rule-node-002/DisabledNodeRule.js
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- rules/dv-rule-pingOneFlow-001/tests/BackToBackKerberosAuthenticationNodes.expect.json
- rules/dv-rule-pingOneFlow-001/tests/BackToBackKerberosAuthenticationNodes.json
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/SubflowRule3.expect.json
- rules/dv-rule-teleport-001/TeleportRule.js
- rules/dv-rule-teleport-001/tests/TeleportRule.expect.json
- Title and recommendation message change , 
- logic change for ui node  subflow, 
- authentication via kerberos back to back node rule
> Title and recommendation message change , logic change for ui node 

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-requiredFields-001/requiredFieldsRule.js
- rules/dv-rule-requiredFields-001/tests/RequiredFieldFlow.expect.json
- rules/dv-rule-requiredFields-001/tests/RequiredFieldFlow.json
- Adding new rule to validate required fields for connector config and capabilities
> Release 1.2.6

- docs/rules.json
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- rules/dv-rule-pingOneFlow-001/tests/BackToBackKerberosAuthenticationNodes.expect.json
- rules/dv-rule-requiredFields-001/requiredFieldsRule.js
- rules/dv-rule-requiredFields-001/tests/RequiredFieldFlow.expect.json
- rules/dv-rule-requiredFields-001/tests/RequiredFieldFlow.json
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/NoSubflowNameSelected.expect.json
- rules/dv-rule-subflow-001/tests/NoSubflowNameSelected.json
- rules/dv-rule-subflow-001/tests/SubflowRule1.expect.json
> DV-19006: Recommended message change and minor bug fixes

- docs/rules.json
- rules/dv-rule-requiredFields-001/requiredFieldsRule.js
- rules/dv-rule-requiredFields-001/tests/RequiredFieldFlow.expect.json
- rules/dv-rule-subflow-001/SubflowRule.js
Recommendation message in Required fields rule minor change
> DV-20193 : Recommendation message in Required fields rule minor change

- rules/dv-rule-requiredFields-001/requiredFieldsRule.js
Added list of connectors for required field rule
> DV-20193: Added list of connectors for required field rule

- docs/rules.json
- rules/dv-rule-AEqualsBMultipleCondition-001/AEqualsBMultipleConditionRule.js
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/AEqualsBMultipleCondition.expect.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-requiredFields-001/requiredFieldsRule.js
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/SubflowRule1.expect.json
- rules/dv-rule-subflow-001/tests/SubflowRule3.expect.json
- rules/dv-rule-validFields-001/ValidFieldsRule.js
- rules/dv-rule-validFields-001/tests/ValidFieldsRule.expect.json
- rules/dv-rule-validFields-001/tests/ValidFieldsRule.json
Some changes in the rules as per feedback from the field
> DV-20324: Changes as per Feedback

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-AEqualsBMultipleCondition-001/AEqualsBMultipleConditionRule.js
- rules/dv-rule-AEqualsBMultipleCondition-001/tests/AEqualsBMultipleCondition.expect.json
- rules/dv-rule-globalVariable-001/GlobalVariableRule.js
- rules/dv-rule-requiredFields-001/requiredFieldsRule.js
- rules/dv-rule-subflow-001/SubflowRule.js
- rules/dv-rule-subflow-001/tests/SubflowRule1.expect.json
- rules/dv-rule-subflow-001/tests/SubflowRule3.expect.json
- rules/dv-rule-validFields-001/ValidFieldsRule.js
- rules/dv-rule-validFields-001/tests/ValidFieldsRule.expect.json
- rules/dv-rule-validFields-001/tests/ValidFieldsRule.json
> Release 1.3.0

- docs/rules.json
- package-lock.json
- package.json
- rules/dv-rule-pingOneFlow-001/PingOneFlowRule.js
- rules/dv-rule-pingOneFlow-001/tests/PingOneFalseNodeRule.expect.json
- rules/dv-rule-pingOneFlow-001/tests/PingOneFalseNodeRule.json
Added rule for PingOne false node
> Release 1.3.1
